sudo: required

services:
- docker

before_install:
- docker pull filcuc/advancedviewsdocker

script:
- docker run -v `pwd`:/root/AdvancedViews filcuc/advancedviewsdocker /bin/bash /root/build.sh ${COVERALLS_REPO_TOKEN}
